---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    env: UAT-env
    app: my-app
  namespace: production
spec:
  containers:
    - name: my-nginx-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
    - name: my-tomcat-instance
      image: tomcat
      ports:
        - name: java
          containerPort: 8080
