
---
apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
  labels:
    env: UAT-env
    app: my-app 
  namespace: production #mention name space name which is  already created
spec:
  type: NodePort
  selector:
    app: my-app # mention here app name we used in labels like this[app: my-app]
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: httpp
      protocol: TCP
      port: 8080
      targetPort: 8080
