apiVersion: v1
kind: Service
metadata:
    name: my-svc-1
    labels:
      env: production
    namespace: prod
spec:
  type: NodePort
  selector:
    name: pod-1
  ports:
    - name: http 
      port: 80